max-ips-allowed: 1
kick-all-players-reload: true # If you disable this and you /reload you will encounter errors.

messages:
  checkconnections: |
    &7-------&c{player}&7-------
    &cIP Address: &7{ip}
    &cActive connections: &7{connections}
  help: | 
    &c/iplimiter - &7Show help (this screen).
    &c/iplimiter reload - &7Reload the configuration of the plugin.
    &c/iplimiter checkconnections <player> - &7Checks the active connections of a user.
  too-many-connections: "&cToo many connections!"
  no-permission: "&cYou don't have the required permission to use this command!"
  offline-player: "&cThis player is not online."
  reloaded: "&cReloaded!"
  server-reload-kick: "&cReloading!"